const hotelStub = {
    get: (url, data) => {
        const stub ={
            data:[
                { land:'Nederland', werelddeel:'Europa', stad:'Den Haag', 
                    hotels:[
                        { naam:'Babylon Hotel', img:require('@/assets/hotel_img/babylon/Babylon.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:128, 
                        beschrijving:[
                            'Het hotel ligt in het hart van Den Haag, op loopafstand van het stadscentrum en alle regeringsgebouwen en ministeries. Het ligt direct naast het centraal station (bussen, trams en treinen), zodat de gasten binnen enkele minuten alle bestemmingen in Den Haag en omgeving kunnen bereiken. De gasten vinden vele restaurants, uitgaansgelegenheden en entertainmentopties binnen een straal van 500 meter van het hotel.',
                            'De kamers bieden airconditioning, centrale verwarming en een badkamer. De met vloerbedekking uitgeruste kamers beschikken over een tweepersoonsbed. Bovendien zijn een kluisje en een minibar beschikbaar. Faciliteiten als een koelkastje en een thee-/koffiezetapparaat veraangenamen het verblijf. Een strijkset is voor extra comfort van de reizigers beschikbaar. Voor vakantiecomfort zorgen een internettoegang, een telefoon, een televisie, een radio en wifi. Een douche en een bad behoren tot de inrichting van de badkamers. Verder is een haardroger aanwezig. Het verblijf biedt niet-rokenkamers.',
                            'Het hotel is gebouwd in 1973. De gasten zullen zich in een van de 143 kamers op hun gemak voelen. Er is een lift voorhanden waarmee de meeste etages bereikbaar zijn. Tot een van de faciliteiten hoort een kluis. Wifi in de gemeenschappelijke ruimtes maakt het de reizigers mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het hotel: een restaurant, een eetzaal en een bar. Er zijn ook winkels. De gasten die met de auto komen, kunnen parkeren in een garage (tegen betaling) of op de parkeerplaats. Ook vertaalservice, roomservice en een wasservice worden aangeboden. Sportieve gasten, die het omliggende landschap op de fiets willen verkennen, zullen de fietsverhuur op prijs stellen.',
                            'Het uiteindelijke ontwerp kwam van architect W.Th. Ellerman[2] van architectenbureau Lucas & Niemeijer. Dit bureau had onder andere het Transitorium en de ministeries van Justitie en Binnenlandse zaken ontworpen en volgens het jackblocksysteem gebouwd. Het gebouwencomplex werd echter ontworpen om volgens de op traditionele wijze te worden gebouwd. Bovenop een volgens Amerikaans model ontworpen shopping mall met een winkel- en horecagedeelte, kwam een in verschillende blokken verdeeld kantorencomplex. Aan de kant van het Koningin Julianaplein en de Bezuidenhoutseweg werd hotel Babylon gesitueerd, terwijl onder de grond twee parkeerkelders kwamen en een ruimte voor tentoonstellingen. Voor het interieur werd hulp ingeroepen bij architecten in het buitenland; architect Janos Bertok uit Parijs ontwierp de winkelpassage, de eveneens in Parijs gevestigde Marc-Henri Hecht en Maurice Lubet ontwierpen de drugstore, terwijl de Brit Peter Glynn Smith het hotel ontwierp. De Fransen zorgden voor een opvallend ontwerp van het centrale plein met een fontein, planten en sculpturen, veel glas en koper.'
                        ],
                            kamers:[{soortKamer:"Standaard kamer", img:require('@/assets/hotel_img/babylon/kamers/kamer1.png'), soortBed:"2 eenpersoonsbedden", maxPersonen:2, prijs:103},{soortKamer:"Superior tweepersoonskamer", img:require('@/assets/hotel_img/babylon/kamers/kamer2.png'), soortBed:"2-3 eenspersoonsbedden", maxPersonen:3, prijs:131}] 
                        },
                        { naam:'Van der Valk', img:require('@/assets/hotel_img/van_der_valk/van_der_valk.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:98, 
                            beschrijving:[
                                'Met bijna honderd hotels en vrijwel overal een familielid aan het roer, is Van der Valk wereldwijd een uniek familiebedrijf. Een grote familie die zo lang intensief samenwerkt, dat zorgt uiteraard voor mooie verhalen. Lees hieronder meer over de oorsprong en het thuis-van-huis gevoel voor zowel de medewerker als de gast.',
                                'In veel restaurants van Van der Valk is deze uitspraak nog wel eens te horen. Er staat een personeelsmaaltijd klaar, betekent dit voor een leek. Het luik verwijst naar de doorgeefschuif, waarmee vroeger in de eerste Van der Valk restaurants de keuken met de zaal verbonden was. En waarom de personeelsmaaltijd een huiskamer genoemd wordt? Omdat deze vroeger in de huiskamer van de familie Van der Valk zelf genuttigd werd. ',
                                'De drie zussen Riet Broeks, El de Bruijn en Wil Polman, horen bij de oudsten van de derde generatie en weten hier nog wel wat over te vertellen. El: “Wij woonden altijd in de zaak de Bijhorst, totdat we met vijf kinderen waren. Een personeelskantine was er toen nog niet, dus kwam iedereen altijd eten in onze huiskamer”. Riet: “Veel personeel was er ook nog niet toen en er liep ook altijd veel familie”. Wil: “Op een gegeven moment was mijn moeder er wel klaar mee. Het was geen echte huiskamer meer met altijd andere mensen over de vloer. We zijn toen verhuisd naar een aangebouwde woning achter het restaurant.',
                                'Martinus Van der Valk was het nakomertje uit een gezin van 24 kinderen. Misschien dat hij daarom wel overal kansen zag en ze greep. ‘Je moet de slaplantjes oprapen die een ander weggooit’ had zijn vader hem ingeprent en dat heeft hij zijn hele leven ter harte genomen. Na het overlijden van zijn moeder in 1929 verkreeg hij hun Boederij De Gouden Leeuw in Voorschoten, met bijbehorend café. Op een handige manier maakte hij gebruik van de kansen die zich voordeden. Zo ruilde hij eens een paard voor een auto, maar de volgende dag wilde het barrel niet meer starten. Om toch een beetje plezier van zijn aanwinst te hebben monteerde Martinus de autowielen onder zijn paardenwagen, nu was deze geruisloos! Andere karrenbezitters kwamen bij Martinus voor banden en hij werd succesvol in de autohandel. Hiervoor was hij veel onderweg en het viel hem op dat je buiten de deur nergens zo lekker kon eten als thuis. Dit was een idee voor het café! Al snel konden de gasten daar ook lekker eten.'
                            ],
                            kamers:[{soortKamer:"Luxe kamer", img:require('@/assets/hotel_img/van_der_valk/kamers/kamer1.png'), soortBed:"2 eenpersoonsbedden", maxPersonen:2, prijs:129},{soortKamer:"Mindervalide kamer", img:require('@/assets/hotel_img/van_der_valk/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:129}] 
                        },
                        { naam:'Park Hotel', img:require('@/assets/hotel_img/park/park.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:116, 
                        beschrijving:[
                            'Dit attractieve hotel bevindt zich in het hart van het stadscentrum. De prachtige tuinen van het paleis Noordeinde en talrijke mogelijkheden om te winkelen, evenals restaurants, bars en musea bevinden zich op slechts enkele meters afstand van het hotel. Een halte van het openbaar vervoer kunt u na ongeveer 1 km bereiken.                            ',
                            "In het hotel staan kamers met airconditioning en een badkamer ter beschikking. Een balkon behoort tot de basisuitrusting van de meeste kamers. Een tweepersoonsbed zorgt voor een aangename nachtrust in de kamers. Bovendien zijn een kluisje, een minibar en een bureau beschikbaar. Ook een koelkast, een koelkastje en een thee-/koffiezetapparaat zijn aanwezig. Een broekenpers is voor extra comfort van de reizigers beschikbaar. Kleine extra's zoals een internettoegang, een telefoon, een televisie en wifi maken het verblijf nog aangenamer. Comfort in de badkamer biedt een douche. Een van de faciliteiten is ook een haardroger. Het verblijf biedt niet-rokenkamers." ,
                            'In 1912 werd het hotel gebouwd. De gasten zijn van harte welkom in het verblijf met 114 kamers. De afzonderlijke etages zijn zonder problemen met de lift of via de trap toegankelijk. Tot een van de faciliteiten hoort een kluis. Wifi in de gemeenschappelijke ruimtes maakt het de reizigers mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het hotel: een restaurant en een bar. Bovendien is er een tuin. De gasten die met de auto komen, kunnen parkeren in een garage of op de parkeerplaats. Ook roomservice en een wasservice worden aangeboden. Sportieve gasten, die het omliggende landschap op de fiets willen verkennen, zullen de fietsverhuur op prijs stellen. '
                        ],
                            kamers:[{soortKamer:"Eenvoudige tweepersoonskamer", img:require('@/assets/hotel_img/park/kamers/kamer1.png'), soortBed:"2 tweepersoonsbed", maxPersonen:2, prijs:130},{soortKamer:"Superior tweepersoonskamer", img:require('@/assets/hotel_img/park/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:158}] 
                        }                    
                    ]
                },
                { land:'Nederland', werelddeel:'Europa', stad:'Amsterdam', 
                    hotels:[
                        { naam:'Hotel Apollofirst', img:require('@/assets/hotel_img/apollofirst/apollofirst.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:101, 
                        beschrijving:[
                            'Dit hotel bevindt zich in een van de schitterendste straten van Amsterdam. Hiervandaan, aan de rand van het centrum, in het culturele hart van Amsterdam bereikt u het Van Gogh Museum, het Stedelijk Museum en het Rijksmuseum binnen enkele minuten lopen. Het World Trade Centre, het Concertgebouw en het Rai congrescentrum bevinden zich op enkele minuten rijafstand. Dit is de ideale plek voor zakenreizigers, op ca. 20 minuten van Schiphol.',
                            'Er worden kamers met een centrale verwarming, een ventilator en een badkamer aangeboden. De met vloerbedekking uitgeruste kamers beschikken over een tweepersoonsbed. Bovendien zijn een kluisje, een minibar en een bureau beschikbaar. Voor optimaal comfort zorgen een internettoegang, een telefoon, een televisie, een radio, een wekker en wifi. Een douche en een bad behoren tot de inrichting van de badkamers. Verder is een haardroger aanwezig. Het verblijf biedt niet-rokenkamers.',
                            'Het hotel beschikt over 40 kamers. In het verblijf worden de gasten hartelijk verwelkomd in de ontvangsthal aan de 24-uurs-receptie en 24-uurs-uitcheckservice. Alle etages zijn gemakkelijk bereikbaar met de lift of via de trap. Tot een van de faciliteiten hoort een kluis. Wifi in de gemeenschappelijke ruimtes maakt het de reizigers mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het hotel: een restaurant, een ontbijtzaal, een koffiehuis en een bar. Bovendien is er een tuin. Tot de verdere voorzieningen van het hotel behoort een krantenkiosk. Tot de beschikbare voorzieningen behoren roomservice en een wasservice.'
                        ],
                            kamers:[{soortKamer:"Comfort tweepersoonskamer", img:require('@/assets/hotel_img/apollofirst/kamers/kamer1.png'), soortBed:"tweepersoonsbed", maxPersonen:2, prijs:134.10},{soortKamer:"DeLuxe tweepersoonskamer", img:require('@/assets/hotel_img/apollofirst/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:147.60}] 
                        },
                        { naam:'Jakarta', img:require('@/assets/hotel_img/jakarta/jakarta.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:186, 
                            beschrijving:[
                                'Ons nieuwste project Hotel Jakarta Amsterdam op het Java-eiland Amsterdam, het ‘groenste’ hotel van Nederland, is begin juni 2018 eindelijk gereed gekomen. In het atrium is in samenwerking met de Hortus Botanicus een subtropische tuin aangelegd en de exploitatie van het hotel is energieneutraal. Daarnaast werken we samen met het Tropenmuseum.',
                                'Hotel Jakarta is ontworpen door SeARCH en is het architectonisch hoogtepunt in de geschiedenis van WestCord Hotels en onze hotelcarrière. Ooit in 1968 begonnen op Waddeneiland Vlieland met Hotel de Wadden heeft ons familiebedrijf nu hotels op Terschelling en Ameland en in Amsterdam, Rotterdam, Delft, Leeuwarden, Garderen en Raalte. Bekijk de WestCord Hotels website voor de hele geschiedenis.',
                                'Twee van onze bekendste hotels zijn het ss Rotterdam en Hotel New York, beiden gevestigd in Rotterdam. En laat nou de geschiedenis van juist deze hotels, als onderdeel van de Holland Amerika-lijn, bijna naadloos aansluiten bij die van de locatie van Hotel Jakarta Amsterdam. Want waar men vroeger vanaf het huidige Hotel New York – voormalig hoofdkantoor van de Holland Amerika-lijn – naar Amerika vertrok, ging men vanaf het Java-eiland naar ‘De Oost’.',
                                'In Amsterdam zijn we inmiddels goed bekend, in 2001 openden we daar Art Hotel Amsterdam, later gevolgd door City Centre Hotel Amsterdam en in 2009 Fashion Hotel Amsterdam. In juni 2018 openden we de deuren van Hotel Jakarta Amsterdam.'
                            ],
                            kamers:[{soortKamer:"Superior", img:require('@/assets/hotel_img/jakarta/kamers/kamer1.png'), soortBed:"tweepersoonsbed", maxPersonen:2, prijs:186.40},{soortKamer:"junior-suite", img:require('@/assets/hotel_img/jakarta/kamers/kamer2.png'), soortBed:"tweepersoonsbed", maxPersonen:2, prijs:178.73}] 
                        }                    
                    ]
                },
                { land:'Nederland', werelddeel:'Europa', stad:'Rotterdam', 
                    hotels:[
                        { naam:'Nhow', img:require('@/assets/hotel_img/nhow/nhow.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:77, 
                        beschrijving:[
                            'nhow Rotterdam is gevestigd in een van de meest iconische gebouwen van Rotterdam, en u kunt daar deel van uitmaken. Verblijf bij ons en geniet van het beste en meest legendarische uitzicht in de stad. nhow is een bar, restaurant, 4-sterrenhotel en een meetinglocatie. 278 hotelkamers (alle kamers met uitzicht, heerlijk comfortabele bedden en roomservice) 11 flexibele vergaderruimten (allemaal met kamerhoge ramen en ruim 3 meter hoge plafonds) 2 restaurants (gourmet menu en een street-food restaurant) espressobar (missie: koffie drinken, cool zijn!) cocktailbar (lokale hotspot, dj’s op vrijdag- en zaterdagavond) Dakterras (voor zonnige middagen, verbluffende zonsondergangen en een fantastisch uitzicht over de skylineN',
                            'In het hotel staan kamers met airconditioning, een centrale verwarming en een badkamer ter beschikking. Een tweepersoonsbed zorgt voor een aangename nachtrust in de kamers. Bovendien zijn een kluisje en een minibar beschikbaar. Ook een koelkastje en een thee-/koffiezetapparaat zijn aanwezig. Voor vakantiecomfort zorgen een internettoegang, een telefoon, een televisie, een radio en wifi. Een douche en een bad behoren tot de inrichting van de badkamers. Een van de faciliteiten is ook een haardroger. Het hotel biedt niet-rokenkamers.',
                            'Het hotel biedt de gasten in totaal 278 kamers. Met de lift zijn de verschillende verdiepingen van het verblijf bereikbaar. Tot de voorzieningen horen een restaurant, een eetzaal, een bar, roomservice en een conferentieruimte. Via wifi krijgen de gasten in de gemeenschappelijke ruimte toegang tot het internet. De gasten die met de auto komen, kunnen parkeren in een garage of op de parkeerplaats.',
                        ],
                            kamers:[{soortKamer:"Standaard kamer", img:require('@/assets/hotel_img/nhow/kamers/kamer1.png'), soortBed:"tweepersoonsbed", maxPersonen:2, prijs:88},{soortKamer:"Superior tweepersoonskamer", img:require('@/assets/hotel_img/nhow/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:99}] 
                        },
                        { naam:'Hilton', img:require('@/assets/hotel_img/hilton/hilton.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:127, 
                            beschrijving:[
                                'Het hotel bevindt zich vlakbij het stadscentrum, ongeveer 250 m van het centraal station van Rotterdam. Hierdoor ligt de winkelwijk met zijn talrijke winkel- en amusementsmogelijkheden op slechts een steenworp afstand van het hotel. De transfertijd naar de luchthaven van Rotterdam is met een taxi ongeveer 15 minuten.',
                                'De kamers bieden airconditioning, centrale verwarming en een badkamer. Kinderbedjes voor kleine reizigers zijn beschikbaar. Bovendien zijn een kluisje en een minibar beschikbaar. In de kitchenette bevinden zich een koelkastje en een thee-/koffiezetapparaat. Een internettoegang, een telefoon, een televisie en wifi ronden het voorzieningenaanbod af. De badkamers beschikken over een douche, een bad en een bidet. Een van de faciliteiten is ook een haardroger. Het verblijf biedt niet-rokenkamers.',
                                'Dit hotel werd gebouwd in 1963. De gasten zullen zich in een van de 252 kamers op hun gemak voelen. Voor de reizigers staan een ontvangsthal en een receptie klaar. Een lift brengt de gasten naar de meeste etages. Faciliteiten als een kluis en een wisselkantoor zorgen voor een comfortabel verblijf. In de gemeenschappelijke ruimtes staat de gasten wifi ter beschikking. Er is een grote keuze aan eetgelegenheden zoals bv. een restaurant en een bar. Er zijn ook winkels. Tot de verdere voorzieningen van het hotel behoort een krantenkiosk. De gasten die met de auto komen, kunnen parkeren in een garage of op de parkeerplaats. Andere service-opties zijn: een oppasservice, roomservice, een wasservice en een kapper.'
                            ],
                            kamers:[{soortKamer:"Twin kamer", img:require('@/assets/hotel_img/hilton/kamers/kamer1.png'), soortBed:"2 eenpersoonsbedden", maxPersonen:2, prijs:175},{soortKamer:"King kamer", img:require('@/assets/hotel_img/hilton/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:177}] 
                        }                    
                    ]
                },
                { land:'Verenigde Arabische Emiraten', werelddeel:'Azië', stad:'Dubai', 
                    hotels:[
                        { naam:'JW Marriott Marquis', img:require('@/assets/hotel_img/jwm/jwm.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:90, 
                        beschrijving:[
                            'De kamers bieden airconditioning, een woonkamer en een badkamer. De meeste wooneenheden bieden uitzicht op zee. De met vloerbedekking uitgeruste kamers beschikken over een kingsize bed. Ook babybedjes en extra bedden kunnen beschikbaar worden gesteld. Bovendien zijn een kluisje, een minibar en een bureau beschikbaar. Faciliteiten als een koelkastje en een thee-/koffiezetapparaat veraangenamen het verblijf. Een strijkset is voor extra comfort van de reizigers beschikbaar. Voor vakantiecomfort zorgen een internettoegang, een telefoon, een televisie, een radio, een stereo-installatie, een cd-speler, een dvd-speler en wifi. Tot de pluspunten van de kamers behoren ook pantoffels en dagbladen. De badkamers zijn uitgerust met een douche en een bad. Een haardroger en badjassen zijn voor het gemak van de gasten beschikbaar. Het hotel biedt gezinskamers en niet-rokenkamers.',
                            'Het hotel biedt de gasten in totaal 1608 kamers. Voor de reizigers staan een ontvangsthal en een receptie klaar. Alle etages zijn gemakkelijk bereikbaar met de lift of via de trap. Tot een van de faciliteiten hoort een kluis. Via wifi krijgen de gasten in de gemeenschappelijke ruimte toegang tot het internet. De volgende gastronomische voorzieningen zijn beschikbaar in het verblijf: een restaurant, een eetzaal en een bar. De gasten die met de auto komen, kunnen deze op het parkeerterrein van het hotel parkeren. Ook een oppasservice, een medische dienst, roomservice en een wasservice worden aangeboden. Daarnaast wordt er een pendeldienst aangeboden.'
                        ],
                            kamers:[{soortKamer:" Deluxe Kamer met Kingsize Bed", img:require('@/assets/hotel_img/jwm/kamers/kamer1.png'), soortBed:"grote tweepersoonsbed", maxPersonen:2, prijs:145},{soortKamer:"Deluxe Kamer met Kingsize Bed en Uitzicht op de Zee", img:require('@/assets/hotel_img/jwm/kamers/kamer2.png'), soortBed:"grote tweepersoonsbed", maxPersonen:2, prijs:157}] 
                        },
                        { naam:'Burj al Arab', img:require('@/assets/hotel_img/burjArab/burjArab.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:1340, 
                            beschrijving:[
                                'Dit luxueuze en adembenemende luxe hotel bevindt zich in het hart van Dubai en is een van de bekendste en duurste hotels ter wereld. De "Arabische toren" is met zijn 321 meter de hoogste ter wereld en het nieuwe highlight van de stad Dubai. Er is geen enkel hotel dat aan dit luxueuze gasthuis kan tippen. Het maakt deel uit van het Jumeirah Beach Resort complex, dat 15 km ten zuiden van Dubai City ligt. Dit unieke, in de vorm van een zeil vormgegeven gebouw staat fier op een kunstmatig eiland, op ongeveer 280 m van het vasteland en wordt door een brug met het vasteland verbonden. Het hotel staat symbool voor de rijkdom van Dubai en is het meest luxueuze hotel ter wereld. De luchthaven van Dubai ligt op ongeveer 25 kilometer afstand van het hotel.',
                                "De kamers bieden airconditioning, een woonkamer, een keuken en een badkamer. Het uitzicht op zee zorgt in vele accommodaties voor een heerlijke atmosfeer. De kamers beschikken over een kingsize bed of een slaapbank. Er zijn gescheiden slaapkamers aanwezig. Ook babybedjes en extra bedden kunnen beschikbaar worden gesteld. Bovendien zijn een kluisje, een minibar en een bureau beschikbaar. Een thee-/koffiezetapparaat behoort ook tot de standaardvoorzieningen. Een strijkset is voor extra comfort van de reizigers beschikbaar. Kleine extra's zoals een internettoegang, een telefoon, een televisie, een radio, een cd-speler, een dvd-speler, een spelcomputer, een wekker en wifi maken het verblijf nog aangenamer. Tot de pluspunten van de kamers behoren ook pantoffels en dagbladen. De badkamers zijn uitgerust met een douche, een bad en een bubbelbad. Een haardroger en badjassen zijn voor het gemak van de gasten beschikbaar. Het hotel biedt niet-rokenkamers.",
                                'Dit hotel werd gebouwd in 1999. De gasten kunnen kiezen uit 202 kamers. Een lift brengt de gasten naar de meeste etages. Faciliteiten als een kluis en een geldautomaat zorgen voor een comfortabel verblijf. Wifi in de gemeenschappelijke ruimtes maakt het de reizigers mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het hotel: een restaurant, een eetzaal en een bar. Er zijn ook winkels. Op het terrein van het verblijf zijn een mooie tuin en een speelplaats te vinden. Tot de verdere voorzieningen van het hotel behoort een speelruimte. De gasten die met de auto komen, kunnen parkeren in een garage of op de parkeerplaats. Tot de beschikbare voorzieningen behoren een oppasservice, roomservice, een wasservice en een kapper. Daarnaast wordt er een pendeldienst aangeboden.'
                            ],
                            kamers:[{soortKamer:"Deluxe Suite met 1 Slaapkamer", img:require('@/assets/hotel_img/burjArab/kamers/kamer1.png'), soortBed:"1 extra groot tweepersoonsbed en 1 slaapbank", maxPersonen:4, prijs:1613},{soortKamer:" Sky Suite met 1 Slaapkamer", img:require('@/assets/hotel_img/burjArab/kamers/kamer2.png'), soortBed:"1 extra groot tweepersoonsbed", maxPersonen:2, prijs:1784}] 
                        }                    
                    ]
                },
                { land:'Italië', werelddeel:'Europa', stad:'Turijn', 
                    hotels:[
                        { naam:'Majestic', img:require('@/assets/hotel_img/majestic/majestic.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:77, 
                        beschrijving:[
                            'Dit hotel bevindt zich in het stadscentrum van Turijn, direct tegenover het station Porta Nuova. Slechts enkele meters van het hotelgebouw bevinden zich de beroemde bezienswaardigheden van de stad, waaronder de Dom van Turijn en de Palazzo Reale, het voormalig koninklijk paleis. Tal van winkel- en amusementsmogelijkheden vindt u in de onmiddellijke omgeving van het hotel. De dichtstbijzijnde halte van het openbaar vervoer vindt u op ongeveer 100 meter afstand. De rijtijd naar de luchthaven Turijn is ongeveer 30 minuten, de afstand is ongeveer 27 kilometer. ',
                            'De kamers bieden airconditioning, centrale verwarming en een badkamer. Een tweepersoonsbed zorgt voor een aangename nachtrust in de kamers. Bovendien zijn een kluisje en een minibar beschikbaar. Ook een koelkastje en een thee-/koffiezetapparaat zijn aanwezig. Een strijkset is voor extra comfort van de reizigers beschikbaar. Een internettoegang, een telefoon, een televisie, een radio en wifi ronden het voorzieningenaanbod af. Tot de extra´s op kamers behoren pantoffels. Sommige kamers zijn rolstoeltoegankelijk. De badkamers beschikken over een douche en een bad. Een haardroger en badjassen zijn voor het gemak van de gasten beschikbaar. Bovendien zijn barrièrevrije badkamers te boeken. Het hotel biedt gezinskamers en niet-rokenkamers. ',
                            'Het hotel werd in 1861 gebouwd. De gasten zijn van harte welkom in het verblijf met 162 kamers. Voor de reizigers staan een ontvangsthal en een receptie klaar. Alle etages zijn gemakkelijk bereikbaar met de lift of via de trap. Tot de voorzieningen behoren een kluis en een wisselkantoor. Wifi in de gemeenschappelijke ruimtes maakt het de gasten mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het hotel: een restaurant, een eetzaal en een bar. De gasten die met de auto komen, kunnen parkeren in een garage of op de parkeerplaats. Ook een oppasservice, een kinderopvang, roomservice en een wasservice worden aangeboden.'                       
                        ],
                            kamers:[{soortKamer:"Standaard kamer", img:require('@/assets/hotel_img/majestic/kamers/kamer1.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:107},{soortKamer:"Superior suite", img:require('@/assets/hotel_img/majestic/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:112}] 
                        },
                        { naam:'NH Piazza Carlina', img:require('@/assets/hotel_img/carlina/carlina.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:186, 
                            beschrijving:[
                                'In het hotel staan kamers met airconditioning, een centrale verwarming en een badkamer ter beschikking. Een balkon behoort tot de basisuitrusting van de meeste kamers. Een tweepersoonsbed zorgt voor een aangename nachtrust in de kamers. Extra bedden kunnen worden aangevraagd. Bovendien zijn een kluisje en een minibar beschikbaar. Ook een koelkastje en een thee-/koffiezetapparaat zijn aanwezig. Voor vakantiecomfort zorgen een internettoegang, een telefoon, een televisie en wifi. De badkamers zijn uitgerust met een douche en een bad. Een haardroger en badjassen zijn voor het gemak van de gasten beschikbaar. Het verblijf biedt niet-rokenkamers.',
                                'De gasten kunnen kiezen uit 160 kamers. Met de lift zijn de verschillende verdiepingen van het hotel bereikbaar. Tot de voorzieningen behoren een bagagedepot en een kluis. Wifi in de gemeenschappelijke ruimtes maakt het de reizigers mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het verblijf: een restaurant, een eetzaal en een bar. Bovendien is er een tuin. De gasten die met de auto komen, kunnen deze op het parkeerterrein van het hotel parkeren. Ook een 24-uurs-beveiligingsdienst, een oppasservice, een transferservice, roomservice en een wasservice worden aangeboden. Sportieve gasten, die het omliggende landschap op de fiets willen verkennen, zullen de fietsverhuur op prijs stellen.',
                            ],
                            kamers:[{soortKamer:"Premium kamer", img:require('@/assets/hotel_img/carlina/kamers/kamer1.png'), soortBed:"tweepersoonsbed", maxPersonen:2, prijs:198},{soortKamer:"Superior suite", img:require('@/assets/hotel_img/carlina/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:112}] 
                        }                    
                    ]
                },
                { land:'Indonesië', werelddeel:'Azië', stad:'Denpasar', 
                    hotels:[
                        { naam:'Hotel NEO Denpasar', img:require('@/assets/hotel_img/neo/neo.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:20, 
                        beschrijving:[
                            'Er worden kamers met airconditioning, een woonkamer en een badkamer aangeboden. Een balkon behoort tot de standaardvoorzieningen van de meeste kamers. Een tweepersoonsbed zorgt voor een aangename nachtrust in de kamers. Bovendien is er een minibar. Voor vakantiecomfort zorgen een internettoegang, een telefoon, een televisie en wifi. In de wooneenheden staan pantoffels klaar voor de gasten. Tot de inrichting van de badkamers behoort een douche.',
                            'Het hotel biedt een kluis, een restaurant, een koffiehuis, een bar, een transferservice, roomservice en een businesscenter. In de gemeenschappelijke ruimtes staat de gasten wifi ter beschikking. Bovendien is er een tuin. De gasten die met de auto komen, kunnen deze op het parkeerterrein van het verblijf parkeren.'
                        ],
                            kamers:[{soortKamer:"Standaard Tweepersoonskamer", img:require('@/assets/hotel_img/neo/kamers/kamer1.png'), soortBed:"2 eenpersoonsbedden", maxPersonen:2, prijs:26},{soortKamer:"Superior tweepersoonskamer", img:require('@/assets/hotel_img/neo/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed ", maxPersonen:2, prijs:26}] 
                        },
                        { naam:'Aston Denpasar Hotel & Convention Center', img:require('@/assets/hotel_img/aston/aston.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:34, 
                            beschrijving:[
                                'De kamers bieden airconditioning, een woonkamer en een badkamer. Een tweepersoonsbed zorgt voor een aangename nachtrust in de kamers. Er zijn gescheiden slaapkamers aanwezig. Bovendien zijn een kluisje, een minibar en een bureau beschikbaar. Ook een koelkastje en een thee-/koffiezetapparaat zijn aanwezig. Een internettoegang, een telefoon, een televisie en wifi ronden het voorzieningenaanbod af. Een douche en een bad behoren tot de inrichting van de badkamers. Een van de faciliteiten is ook badjassen.',
                                'De gasten kunnen kiezen uit 215 kamers. In het hotel worden de gasten hartelijk verwelkomd in de ontvangsthal aan de 24-uurs-receptie en 24-uurs-uitcheckservice. Tot een van de faciliteiten hoort een kluis. Via wifi krijgen de gasten in de gemeenschappelijke ruimte toegang tot het internet. De volgende gastronomische voorzieningen zijn beschikbaar in het hotel: een restaurant en een eetzaal. Er zijn ook winkels. De gasten die met de auto komen, kunnen deze op het parkeerterrein van het verblijf parkeren. Ook een oppasservice, een kinderopvang, een transferservice, roomservice en een wasservice worden aangeboden.'
                            ],
                            kamers:[{soortKamer:"Suite met één slaapkamer", img:require('@/assets/hotel_img/aston/kamers/kamer1.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:62.24},{soortKamer:"2-Slaapkamer Suite", img:require('@/assets/hotel_img/aston/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:93.20}] 
                        }                    
                    ]
                },
                { land:'Verenigd Koninkrijk', werelddeel:'Europa', stad:'London', 
                    hotels:[
                        { naam:'InterContinental London Park Lane', img:require('@/assets/hotel_img/parkLane/parkLane.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:500, 
                        beschrijving:[
                            'Het moderne first-class hotel ligt central en is een top adres voor veeleisende gasten met een voorliefde voor kwaliteit en competentie. Het hotel beschikt over een uitstekende aansluiting aan het lokale metronet en het is een ideaal vertrekpunt voor het verkennen van de verschillende toeristische attracties en tal van winkels en amusementsmogelijkheden. Binnen enkele minuten bereikt u het metrostation Hyde Park Corner. Bovendien heeft u met de Piccadilly Line een directe aansluiting op de luchthaven Heathrow.'
                        ],
                            kamers:[{soortKamer:"Superior kamer", img:require('@/assets/hotel_img/parkLane/kamers/kamer1.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:590},{soortKamer:"Mayfair Room", img:require('@/assets/hotel_img/parkLane/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:537.34}] 
                        },
                        { naam:'Staybridge Suites London - Vauxhall', img:require('@/assets/hotel_img/stayBridge/stayBridge.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:58, 
                            beschrijving:[
                                "De kamers bieden airconditioning en een keuken. Kinderbedjes voor kleine reizigers zijn beschikbaar. Bovendien is er een kluisje. Er is in elke kamer een kitchenette met een koelkast, een magnetron en een thee-/koffiezetapparaat. Kleine extra's zoals een internettoegang, een televisie en wifi maken het verblijf nog aangenamer. Het hotel biedt niet-rokenkamers."
                            ],
                            kamers:[{soortKamer:"Studio suite", img:require('@/assets/hotel_img/stayBridge/kamers/kamer1.png'), soortBed:"2 eenpersoonsbedden", maxPersonen:2, prijs:160},{soortKamer:"Superior tweepersoonskamer", img:require('@/assets/hotel_img/stayBridge/kamers/kamer2.png'), soortBed:"1 groot tweepersoonsbed", maxPersonen:2, prijs:165}] 
                        }                    
                    ]
                },
                { land:'Italië', werelddeel:'Europa', stad:'Rome', 
                    hotels:[
                        { naam:'Hotel degli Aranci', img:require('@/assets/hotel_img/degli/degli.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:58, 
                        beschrijving:[
                            'Dit attractieve cityhotel van de betere middenklasse bevindt zich in Parioli, de elegante stadswijk van Rome, direct achter de Villa Borghese. Het hotel is rustig gelegen aan een door eikenbomen en sinaasappelbomen omzoomde allee, waar u heerlijk kunt wandelen en van de tijd kunt genieten. Naar het beroemde Auditorium is het slechts ongeveer 10 minuten. Talrijke attractieve mogelijkheden om te winkelen en excellente restaurants kunt u met een korte wandeling bereiken. Naar de wereldberoemde Via Veneto is het ongeveer 3 km. De dichtstbijzijnde luchthaven Ciampino ligt op ca. 30 km afstand, de luchthaven Fiumcino bereikt u na ca. 35 km.',
                            'Er worden kamers met airconditioning, een centrale verwarming en een badkamer aangeboden. In de meeste kamers biedt het balkon een mooi uitzicht. De kamers beschikken over een tweepersoonsbed of een kingsize bed. Bovendien zijn een kluisje, een minibar en een bureau beschikbaar. Een koelkastje behoort ook tot de standaardvoorzieningen. Voor vakantiecomfort zorgen een internettoegang, een telefoon, een televisie en wifi. Een douche en een bad behoren tot de inrichting van de badkamers. Verder is een haardroger aanwezig. Het verblijf biedt gezinskamers en niet-rokenkamers.',
                            'Het hotel beschikt over 58 kamers. Alle etages zijn gemakkelijk bereikbaar met de lift of via de trap. Tot de voorzieningen horen een kluis, een restaurant, een eetzaal, een bar, roomservice en een conferentieruimte. Via wifi krijgen de gasten in de gemeenschappelijke ruimte toegang tot het internet. Bovendien is er een tuin. De gasten die met de auto komen, kunnen deze op het parkeerterrein van het hotel parkeren.'
                        ],
                            kamers:[{soortKamer:"Standaard tweepersoonskamer", img:require('@/assets/hotel_img/degli/kamers/kamer1.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:51},{soortKamer:"Driepersoonskamer", img:require('@/assets/hotel_img/degli/kamers/kamer2.png'), soortBed:"1 kingsize bed en 1 eenpersoonsbed", maxPersonen:4, prijs:66}] 
                        },
                        { naam:'Hotel Indigo Rome - St. George', img:require('@/assets/hotel_img/indigo/indigo.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:101, 
                            beschrijving: [
                                "Het hotel ligt in het hart van de oude stad Rome, op slechts een steenworp afstand van Campo dei Fiori (600 meter), Piazza Navona (700 meter), Vaticaanstad (800 meter) en Castel Sant'Angelo. Het hotel ligt aan de Via Giulia, in een van de meest betoverende gedeeltes van de stad. Het stadscentrum en de winkels liggen op ongeveer 200 meter en de bushalte (aansluiting op buslijn 116) ligt op ongeveer 20 meter van het hotel. De luchthaven Rome Ciampino ligt op circa 25 kilometer en de luchthaven Rome Fiumicino is ongeveer op 35 kilometer van het hotelperceel.",
                                "In het hotel staan kamers met airconditioning, een centrale verwarming en een badkamer ter beschikking. Een balkon behoort tot de basisuitrusting van de meeste kamers. Een tweepersoonsbed zorgt voor een aangename nachtrust in de kamers. Bovendien zijn een kluisje en een minibar beschikbaar. Ook een koelkastje en een thee-/koffiezetapparaat zijn aanwezig. Voor vakantiecomfort zorgen een internettoegang, een telefoon, een televisie en wifi. Er zijn rolstoeltoegankelijke kamers te boeken. De badkamers zijn uitgerust met een douche en een bad. Een haardroger en badjassen zijn voor het gemak van de gasten beschikbaar. Bovendien zijn barrièrevrije badkamers te boeken. Het verblijf biedt niet-rokenkamers.",
                                "Het hotel is gebouwd in 1805. Het van airconditioning voorziene hotel biedt 64 kamers. Er is een lift voorhanden waarmee de meeste etages bereikbaar zijn. Faciliteiten als een garderobe en een wisselkantoor zorgen voor een comfortabel verblijf. Wifi in de gemeenschappelijke ruimtes (tegen betaling) maakt het de reizigers mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het verblijf: een restaurant, een eetzaal, een ontbijtzaal en een koffiehuis. Bovendien is er een tuin. De gasten die met de auto komen, kunnen deze op het parkeerterrein van het hotel parkeren. Ook roomservice en een wasservice worden aangeboden."
                            ],
                            kamers:[{soortKamer:"Standaard kamer", img:require('@/assets/hotel_img/indigo/kamers/kamer1.png'), soortBed:"2 eenpersoonsbedden", maxPersonen:2, prijs:173.40},{soortKamer:"Superior tweepersoonskamer", img:require('@/assets/hotel_img/indigo/kamers/kamer2.png'), soortBed:"1 tweepersoonsbed", maxPersonen:2, prijs:201.60}] 
                        }                    
                    ]
                },
                { land:'Verenigde Staten', werelddeel:'Amerika', stad:'New York', 
                    hotels:[
                        { naam:'InterContinental New York Barclay', img:require('@/assets/hotel_img/barclay/barclay.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:62, 
                        beschrijving:[
                            "Dit luxehotel is rijk aan traditie en ligt in het hart van de stad en vlakbij de Park Avenue. Bars, restaurants, winkels, nachtclubs en openbaar vervoerverbindingen bevinden zich op slechts meters van het hotel.",
                            "De kamers bieden airconditioning, centrale verwarming en een badkamer. De van vloerbedekking voorziene kamers beschikken over een tweepersoonsbed of een kingsize bed. Bovendien zijn een kluisje en een minibar beschikbaar. Faciliteiten als een koelkastje en een thee-/koffiezetapparaat veraangenamen het verblijf. Een strijkset is voor extra comfort van de reizigers beschikbaar. Een internettoegang, een telefoon, een televisie, een radio, een wekker en wifi zijn vanzelfsprekend ook aanwezig op de kamers. Er zijn rolstoeltoegankelijke kamers te boeken. De badkamers beschikken over een douche en een bad. Een haardroger en badjassen zijn voor het gemak van de gasten beschikbaar. Bovendien zijn barrièrevrije badkamers te boeken. Het verblijf biedt niet-rokenkamers.",
                            "Het hotel werd in 1920 gebouwd. De gasten zijn van harte welkom in het verblijf met 686 kamers. In het van airconditioning voorziene hotel worden de gasten hartelijk verwelkomd in de ontvangsthal aan de 24-uurs-receptie en 24-uurs-uitcheckservice. Alle etages zijn gemakkelijk bereikbaar met de lift of via de trap. Tot de voorzieningen behoren een garderobe, een kluis en een wisselkantoor. Wifi in de gemeenschappelijke ruimtes maakt het de reizigers mogelijk om in contact te blijven met vrienden of familieleden. De volgende gastronomische voorzieningen zijn beschikbaar in het hotel: een restaurant, een eetzaal en een bar. In de souvenirwinkel kunnen de gasten souvenirs en geschenken kopen. De gasten die met de auto komen, kunnen parkeren in een garage (tegen betaling) of op de parkeerplaats (tegen betaling). Ook een oppasservice, roomservice en een wasservice worden aangeboden."
                        ],
                            kamers:[{soortKamer:"Superior kamer", img:require('@/assets/hotel_img/barclay/kamers/kamer1.png'), soortBed:"1 queensize bed", maxPersonen:2, prijs:186},{soortKamer:"Executive kamer, 1 kingsize bed", img:require('@/assets/hotel_img/barclay/kamers/kamer2.png'), soortBed:"1 kingsize bed,", maxPersonen:2, prijs:217}] 
                        },
                        { naam:'Park Central Hotel New York', img:require('@/assets/hotel_img/central/central.png'), voorzieningen:[{naam:"Wifi", img:require('@/assets/voorzieningen/wifi.png')}, {naam:"Restaurant", img:require('@/assets/voorzieningen/restaurant.png')}, {naam:"Fitness", img:require('@/assets/voorzieningen/fitness.png')}, {naam:"Zwembad", img:require('@/assets/voorzieningen/zwembad.png')}, {naam:"Naast het Station", img:require('@/assets/voorzieningen/station.png')}],prijs:95, 
                            beschrijving: [
                                "De kamers bieden airconditioning, centrale verwarming en een badkamer. De met vloerbedekking uitgeruste kamers beschikken over een kingsize bed. Kinderbedjes voor kleine reizigers zijn beschikbaar. Bovendien is er een kluisje. Een thee-/koffiezetapparaat behoort ook tot de standaardvoorzieningen. Een strijkset is voor extra comfort van de gasten beschikbaar. Kleine extra's zoals een internettoegang, een telefoon, een televisie, een radio, een wekker en wifi maken het verblijf nog aangenamer. Er zijn rolstoeltoegankelijke kamers te boeken. De badkamers zijn uitgerust met een douche en een bad. Verder is een haardroger aanwezig. Bovendien zijn barrièrevrije badkamers te boeken. Het hotel biedt gezinskamers en niet-rokenkamers.",
                                "Het hotel is gebouwd in 1920. Het hotel biedt de reizigers in totaal 915 kamers. Een lift brengt de gasten naar de meeste etages. Faciliteiten als een garderobe, een kluis en een geldautomaat zorgen voor een comfortabel verblijf. Wifi in de gemeenschappelijke ruimtes (tegen betaling) maakt het de gasten mogelijk om in contact te blijven met vrienden of familieleden. Er is een grote keuze aan eetgelegenheden zoals bv. een restaurant, een eetzaal, een koffiehuis en een bar. Het is mogelijk om inkopen te doen in een supermarkt en een souvenirwinkel en andere winkels. Tot de verdere voorzieningen van het verblijf behoort een krantenkiosk. De gasten die met de auto komen, kunnen parkeren in een garage (tegen betaling) of op de parkeerplaats (tegen betaling). Tot de beschikbare voorzieningen behoren roomservice en een wasservice."
                            ],
                            kamers:[{soortKamer:"Klassieke kamer", img:require('@/assets/hotel_img/central/kamers/kamer1.png'), soortBed:"1 kingsize bed", maxPersonen:2, prijs:130},{soortKamer:"Klassieke kamer", img:require('@/assets/hotel_img/central/kamers/kamer2.png'), soortBed:"1 kingsize bed", maxPersonen:2, prijs:138}] 
                        }                    
                    ]
                },
                
            ]
        };
        return Promise.resolve(stub);
    }
};

export default hotelStub;